# --- PUBLIC METADATA ---
title: Orthogonal Thoughts
description: by Trailmind

# GitHub Pages requires themes to be set via remote_theme instead of the standard theme option
# remote_theme: username/repo
# ... unless we are using the github-pages supported theme
theme: jekyll-theme-slate
google_analytics: G-FNMDX3KNFD

# --- INFRASTRUCTURE EXCLUDES ---
# These are kept in public to keep the live website (_site) clean.
exclude:
  - __local
  - Keepfile
  - Gemfile
  - Gemfile.lock
  - _site
  - .devcontainer
  - .bundle/
  - vendor/
  - node_modules/
  - .jekyll-cache/
  - .jekyll-metadata
